# Turns a data file into a C++ source that exposes it as a byte array.
#
#   cmake -DINPUT=<file> -DOUTPUT=<file.cpp> -DSYMBOL=<name> -P EmbedFile.cmake
#
# The generated file defines `const unsigned char <SYMBOL>[]` and
# `const std::size_t <SYMBOL>_size` in namespace occ::embedded. Used for the
# DFT-D4 reference data so a bare executable works without OCC_DATA_PATH.
if(NOT INPUT OR NOT OUTPUT OR NOT SYMBOL)
    message(FATAL_ERROR "EmbedFile.cmake needs INPUT, OUTPUT and SYMBOL")
endif()
file(READ "${INPUT}" _hex HEX)
string(LENGTH "${_hex}" _hex_len)
math(EXPR _size "${_hex_len} / 2")
string(REGEX REPLACE "([0-9a-f][0-9a-f])" "0x\\1," _bytes "${_hex}")
# 16 bytes per line keeps the file readable and the compiler happy.
string(REGEX REPLACE "((0x[0-9a-f][0-9a-f],){16})" "\\1\n" _bytes "${_bytes}")
file(WRITE "${OUTPUT}"
"// Generated by cmake/EmbedFile.cmake from ${INPUT}. Do not edit.
#include <cstddef>
namespace occ::embedded {
extern const unsigned char ${SYMBOL}[];
extern const std::size_t ${SYMBOL}_size;
const unsigned char ${SYMBOL}[] = {
${_bytes}
};
const std::size_t ${SYMBOL}_size = ${_size};
} // namespace occ::embedded
")
