name: Build python wheels

on:
  push:
    tags: "v*"
  pull_request:
    tags: "v*"


jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        pyver: [cp39, cp310, cp311, cp312]

    steps:
      - name: Checkout repos
        uses: actions/checkout@v3

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.16.1
        env:
          CIBW_BUILD: ${{matrix.pyver}}-*
          CIBW_ARCHS_LINUX: auto
          CIBW_ARCHS_MACOS: auto universal2
          CIBW_ARCHS_WINDOWS: auto
          CIBW_TEST_SKIP: *

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl
          name: wheels

  upload_all:
    runs-on: ubuntu-latest
    needs: build_wheels
    environment:
      name: pypi
      url: https://pypi.org/p/occpy/
    permissions:
      id-token: write
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
    steps:
    - uses: actions/download-artifact@v3
      with:
        name: wheels 
        path: dist

    - uses: pypa/gh-action-pypi-publish@release/v1
